### ISSUE TITLE
Compare solution in Section 5.5.1 with radially symmetric solution?

### ISSUE THREAD

**Issue by ketch** [ketch/circular_hydraulic_jump#11]
At the end of this section, we claim that the Rusanov solution is less accurate.  I think that if we want to say this then we should compare the solutions with that obtained by assuming radial symmetry (from Section 2).

**Comment by manuel-quezada** [comment]
You deleted that line in a previous PR and I agree with that. I think we can close this issue unless we still want to add a comparison.
